"""cascade_delete

Revision ID: 3be526b5b86b
Revises: d350b33f4c13
Create Date: 2022-06-16 12:36:54.755111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3be526b5b86b'
down_revision = 'd350b33f4c13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_categorie',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('categorie_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='article_categorie_article_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories.id'], name='article_categorie_categorie_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='article_categorie_pkey')
    )
    # ### end Alembic commands ###
