"""categorie id in article

Revision ID: 66cc2579aefb
Revises: a669a2edf309
Create Date: 2022-06-15 11:10:31.383263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66cc2579aefb'
down_revision = 'a669a2edf309'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('categorie_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articles', 'categories', ['categorie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'categorie_id')
    # ### end Alembic commands ###
