"""add CategorieArticle table

Revision ID: 8af4fa6df736
Revises: 66cc2579aefb
Create Date: 2022-06-15 13:52:09.746326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8af4fa6df736'
down_revision = '66cc2579aefb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
