"""add column last modified in users

Revision ID: af1bf881db51
Revises: 30bc6bfc6d4f
Create Date: 2022-06-17 16:01:59.430385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af1bf881db51'
down_revision = '30bc6bfc6d4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_modified')
    # ### end Alembic commands ###
