"""delete categori id from categorie

Revision ID: d350b33f4c13
Revises: 4d71a3e33e38
Create Date: 2022-06-15 14:32:32.584996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd350b33f4c13'
down_revision = '4d71a3e33e38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('articles_categorie_id_fkey', 'articles', type_='foreignkey')
    op.drop_column('articles', 'categorie_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('categorie_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('articles_categorie_id_fkey', 'articles', 'categories', ['categorie_id'], ['id'])
    op.create_table('article_categorie',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('categorie_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='article_categorie_article_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories.id'], name='article_categorie_categorie_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='article_categorie_pkey')
    )
    # ### end Alembic commands ###
